## define selfsigned cert issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
## config selfsigned ca certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "example-ca-cert"
  namespace: cert-manager
# https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.Certificate
spec:
  isCA: true
  commonName: "Example Inc Selfsigned CA"
  secretName: "example-ca-secret"
  duration: 87600h
  renewBefore: 336h
  subject:
    countries:
      - "CN"
    provinces:
      - "Zhejiang"
    localities:
      - "Hangzhou"
    organizations:
      - "Example Inc CA"
    organizationalUnits:
      - "CA"
  dnsNames:
    - "www.example.com"
  emailAddresses:
    - "ops@example.com"
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: "selfsigned-issuer"
    kind: ClusterIssuer
    group: cert-manager.io
---
# https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.ClusterIssuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: example-ca-issuer
spec:
  ca:
    secretName: example-ca-secret
