# https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/docs/driver-parameters.md
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-21
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.21
  share: /data/nfs_share
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
